### ISSUE TITLE
What is the use of fastapi.params

### ISSUE THREAD

**Issue by pnijhara** [PacktPublishing/Building-Data-Science-Applications-with-FastAPI#1]
In chapter 7, the author has written from `fastapi.params import Depends`
https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/blob/main/chapter7/chapter7_api_key_header.py#L2

I don't find any use in it. Can @frankie567 clarify this? Maybe, I am wrong.

**Comment by frankie567** [comment]
Good catch, thanks! It's a remainder of a wrong automatic import. I'll fix it right away!
