### ISSUE TITLE
Refering to python built-in `id` instead of `comment.post_id` in HTTPException?

### ISSUE THREAD

**Issue by gitgithan** [PacktPublishing/Building-Data-Science-Applications-with-FastAPI#11]
I found this happening in 2 places by searching `detail=f"Post` in vscode.
1. https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/blob/main/chapter6/sqlalchemy_relationship/app.py#L124
2. https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/blob/main/chapter6/tortoise_relationship/app.py#L80

On the front-end, the interpolated string looks like it's printing some information about a function instead of the post id. I guess the python built-in `id` was used when it should be `comment.post_id`?

**Comment by frankie567** [comment]
Whoops! That's indeed a mistake on my part!

You're right the correct way would be:

```py
detail=f"Post {comment.id} does not exist"
```

and:

```py
detail=f"Post {comment.post_id} does not exist"
```

I'll fix this right away and coordinate a fix with Packt!

Thank you for your help 🙏

**Comment by frankie567** [comment]
Fixed in https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/commit/34d40b4779fc9bcd1a12d6f425a8f78db02a25bd
