### ISSUE TITLE
[Chapter 6] comment argument in create_comment() as CommentCreate instance

### ISSUE THREAD

**Issue by AlessandroMiola** [PacktPublishing/Building-Data-Science-Applications-with-FastAPI#12]
Hi François, first off, thanks for your amazing book! Very straight to the point in presenting the core concepts of FastAPI and its ecosystem :)

I'd just like to point out a possible typo (though quite irrelevant) in the [`create_comment`](https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/blob/a1e4ea72a06c31e96b07c45432d1b18bd45fd744/chapter6/tortoise_relationship/app.py#L75) definition in `Tortoise` section. If I'm not wrong, in the spirit of the previous examples the `comment` argument should rather be type-hinted as a `CommentCreate` instance.

**Comment by frankie567** [comment]
Hi @AlessandroMiola 👋 

Yes, you're right! In this case, it doesn't make much difference, but it should definitely be `CommentCreate`!

Packt and I are currently working on a Second Edition of the book, set to release this summer. Stay tuned!
