### ISSUE TITLE
excute(update_query) return influenced rows

### ISSUE THREAD

**Issue by 66dexmg** [PacktPublishing/Building-Data-Science-Applications-with-FastAPI#5]
https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/blob/da186755fba69a56917a222caa19661a8c19fc8b/chapter6/sqlalchemy/app.py#L91
I have tried in my code.Maybe the method 'execute' for 'update' return influenced rows not the primary-key id.And I know that in the  'insert' condition new id was returned.
So maybe 'post.id' should be the parameter instead of 'post_id' in next function.

**Comment by frankie567** [comment]
Hi @66dexmg 👋 

Do you get a specific error when doing this?

**Comment by frankie567** [comment]
You're perfectly right @66dexmg, that's actually quite a dumb mistake from my part. You can find the correct, fixed code here: https://github.com/PacktPublishing/Building-Data-Science-Applications-with-FastAPI/commit/e95e35f484809e937071e45a3c1f6fcab83fd8f7

I'll now contact Packt to coordinate a proper erratum. Thank you for raising this 🙏

**Comment by 66dexmg** [comment]
@frankie567
You are welcome.You have written a fantastic book although I had waitted its Chinese translation for a long time😀.Any oriented advice for me after I finish it?

**Comment by 66dexmg** [comment]
Thanks a lot!
